name: vircon_client
description: "A mobile client for The Vircon Project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  async: ^2.13.0
  dart_mappable: ^4.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.8.0
  dart_mappable_builder: ^4.6.1

flutter:
  uses-material-design: true
